### ISSUE TITLE
Public artifacts

### ISSUE THREAD

**Issue by juanjovazquez** [Sphonic/sphonic-phantom#3]
Could I find this artifact published in any OSS repository?. Thanks in advance.

**Comment by melodious** [comment]
+1

**Comment by juanjovazquez** [comment]
@melodious for the time being you have this library published on Tecsisa's bintray sbt-plugins repo. In your plugins.sbt:

``` scala
resolvers += Resolver.url("sbt-plugins", url("http://dl.bintray.com/tecsisa/sbt-plugins"))(Resolver.ivyStylePatterns)

addSbtPlugin("com.sphonic" % "phantom-sbt" % "0.3.0") 
```

**Comment by melodious** [comment]
@juanjovazquez Thanks. Unfortunately, I need scala 2.11

**Comment by juanjovazquez** [comment]
@melodious It's just a plugin. You should be able to make it work with Scala 2.11. [Here](https://github.com/Tecsisa/reactive-cassandra-phantom) you have an example of use with Scala 2.11.7. Hope this helps.

**Comment by MerlinDMC** [comment]
I got 0.3.2 published to bintray (the sbt plugin and the connector) under a sphonic organisation.

https://bintray.com/sphonic

Feel free to use it from there.
The sbt plugin is compiled with 2.10.5 only since it is a plugin for sbt.
The connector is cross compiled for 2.10.5 and 2.11.7.

**Comment by juanjovazquez** [comment]
Thanks!. I'll start using it from there.

**Comment by juanjovazquez** [comment]
@MerlinDMC I had problems doing this work. SBT expects the plugin publlished following the ivy style pattern.

**Comment by MerlinDMC** [comment]
ofc it does.

Ye let me reconfigure and push again - the scala dependency jungle will kill me some day.

**Comment by MerlinDMC** [comment]
@juanjovazquez works for me now ... I edited the linked repo to pull from our repo.

``` diff
diff --git a/project/plugins.sbt b/project/plugins.sbt
index 3e32ae1..d5b6352 100644
--- a/project/plugins.sbt
+++ b/project/plugins.sbt
@@ -1,9 +1,9 @@
 // for sphonic-phantom
-resolvers += Resolver.url("sbt-plugins", url("http://dl.bintray.com/tecsisa/sbt-plugins"))(Resolver.ivyStylePatterns)
+resolvers += Resolver.url("sbt-plugins", url("https://dl.bintray.com/sphonic/sbt-plugins/"))(Resolver.ivyStylePatterns)

 addSbtPlugin("me.lessis" % "bintray-sbt" % "0.3.0")

-addSbtPlugin("com.sphonic" % "phantom-sbt" % "0.3.0")
+addSbtPlugin("com.sphonic" % "phantom-sbt" % "0.3.2")

 addSbtPlugin("com.jsuereth" % "sbt-pgp" % "1.0.0")
```

**Comment by juanjovazquez** [comment]
It worked like a charm. I'll close the issue then. Thanks!.

**Comment by melodious** [comment]
cool! thanks!
